
title: Data-Blog
theme: "jekyll-theme-hacker"
description: "Big Data Tech's(in progress)"
author:
  name: "Jeff"
  email: "jefferalmache@gmail.com"
  url: "https://jeff1191.github.io/datablog/"
paginate: 7
include: [_pages, _docs]

gems: [jekyll-paginate, jekyll-seo-tag]
